### ISSUE TITLE
Ability to limit memory and performance

### ISSUE THREAD

**Issue by dobegor** [milochristiansen/lua#14]
Hi!

I've recently encountered your VM and I'm interested if there's any way to add maximum memory and performance (instructions per second) limit. That would be very useful for embedding the VM into a game with programmable "computers", to prevent players crashing server with too much memory allocated and hanging the server CPU.

**Comment by milochristiansen** [comment]
In short: No

Well, yes, but parts of the VM would need a rewrite. Right now you call into the VM and it runs whatever you called until it is finished, there is no support for pausing and resuming execution (which is what you would need to do to limit speed). Memory would be much simpler (just adding a check to make sure the stack does not get larger than a certain size would take care of most of it), but honestly lagging the CPU would be a much more important issue to prevent (since it would be so easy to do with a loop or whatever).

So, it would be possible, but you would need to re-write the main loop of the VM, and change the way execution state is saved. The API would need major changes to keep track of what is running and allow stepping the execution engine by a timeslice.

I say "you" because to be honest, if I was planning to write a new VM I would be doing it for another language. I fix any bugs that come up in this one, but major reworking is not in my plans. You are, of course, welcome to use this VM as the base for your own work, it should at least save you some time.

**Comment by dobegor** [comment]
Thanks for a detailed response!

The reason I'm asking is that we are evaluating our options for in-game programmable computers.
> just adding a check to make sure the stack does not get larger

What about dynamically allocated memory? Or does it only use stack + program memory?

> since it would be so easy to do with a loop or whatever

Yes, that will require evaluating loop execution differently.

We already have a simple VM (https://github.com/db47h/ngaro) which does not have a high level language to program it (except the assembly). Porting your Lua compiler to produce code for it seems a task that isn't much easier than modifying your VM so I was just asking if there are any plans for doing it :)

> You are, of course, welcome to use this VM as the base for your own work, it should at least save you some time.

Sure, we are going to do it ourselves. Awesome thanks for publishing this on github!

**Comment by milochristiansen** [comment]
> What about dynamically allocated memory? Or does it only use stack + program memory?

Table indexes are dynamic, they would be much (much, much) harder to limit.

> We already have a simple VM

If you are not too stuck on Lua, it would probably be easier to write a FORTH or something for your existing VM. (Oh, wait, I just realized Ngaro is *designed* to run FORTH, so that makes it an even more attractive option.) Another good option would be some kind of BASIC.

Compiling Lua for that VM will not work. In theory it would be possible, but it would basically require running a VM on your VM.

**Comment by dobegor** [comment]
We specifically decided to drop FORTH support because we wanted to pick something more user-friendly. Also, we're kind of targeting a specific audience that might played Minecraft with [OpenComputers](https://ocdoc.cil.li/) mod, which provides Lua-programmable computers, so we thought it'd be nice to pick Lua, despite it's harder to implement it.

Anyway, thank you for the tips!

**Comment by milochristiansen** [comment]
Well, Good luck!
