### ISSUE TITLE
Method on table fails to modify table state

### ISSUE THREAD

**Issue by jeff-emanuel** [milochristiansen/lua#16]
The following code does not change buffer as it does in Lua 5.3.4:

	obj = { buffer = {} }
	function obj.append(self,value) self.buffer[#self.buffer+1] = value end
	obj:append(7)
	print(#obj.buffer)
	for i,v in ipairs(obj.buffer) do print(i,v) end

It also does not work when passing an explicit self parameter:

	obj = { buffer = {} }
	function obj.append(self,value) self.buffer[#self.buffer+1] = value end
	obj.append(obj,7)
	print(#obj.buffer)
	for i,v in ipairs(obj.buffer) do print(i,v) end

The attached code prints 0 twice.

[luamethod.zip](https://github.com/milochristiansen/lua/files/2507251/luamethod.zip)

**Comment by milochristiansen** [comment]
Initial testing indicates a compiler error, as code compiled with `luac` works properly. I still need to identify where it is going wrong, but a fix should be available within the day.

**Comment by jeff-emanuel** [comment]
Thanks!

**Comment by milochristiansen** [comment]
Ok, the problem was pretty obvious once I thought to examine the object with `pairs` instead of `ipairs`. Turns out the compiler was using the same register for both key and value.

The issue was caused by the code that compiled identifiers not properly indicating how many registers it used in certain cases. I'll push the fix in the next minute or so. Hopefully it fixes all such cases, but if not let me know.

**Comment by jeff-emanuel** [comment]
Thanks again for the prompt response.  It looks good.
