### ISSUE TITLE
Find a bug about literal string.

### ISSUE THREAD

**Issue by erdian718** [milochristiansen/lua#28]
`assert(string.byte('\xc0') == 192)`

**Comment by milochristiansen** [comment]
This is an interesting bug, that I am not 100% sure how to fix. At first I thought that there was a bug in my string parsing, but it turns out `U+00C0` is encoded in UTF8 as `195 128`. Since strings are built in the lexer one character at a time and stored in a `rune` slice (the lexer does everything in `rune`s), there isn't really a way to keep it from not encoding the final result the way things are written.

I could probably rewrite the string literal code to hold everything in a byte slice and do the encoding manually where needed, I'll see when I start digging deeper into the code in a few minutes.
