### ISSUE TITLE
I'm not sure if it is a BUG?

### ISSUE THREAD

**Issue by erdian718** [milochristiansen/lua#29]
```go
l.LoadText(strings.NewReader(`
	function test()
		return print()
	end
`), "", 0)
l.Call(0, 0)
l.Push("BUG?")
l.Push("test")
l.GetTableRaw(lua.GlobalsIndex)
l.Call(0, 1)
println(l.ToString(-1)) // `nil` is expected
```

**Comment by milochristiansen** [comment]
When you call a function as the only argument to a return, it does a tail call (replacing the existing stack frame instead of adding a new one). The tail call code assumes the future `RETURN` instruction knows what it is doing and just rolls with whatever returned value count it is given, completely ignoring the value specified in `Call`.

This is most likely a bug. I'll fix it in a few minutes assuming the fix doesn't break anything else in fun and interesting ways.
