### ISSUE TITLE
where is tutorial!?

### ISSUE THREAD

**Issue by aggronmagi** [milochristiansen/lua#3]
where is tutorial!?
how to load and run a function after I load a lua file!?
3q!

**Comment by milochristiansen** [comment]
There is an example showing how you load a script, if you want to know how to create a native function there are lots of examples in the standard modules. RTFM, I won't hold your hand.

If you want to run a script function from native code you first need to know where the function is and how to get to it. This is not in any way specific to my VM, you need to know how to use Lua as an embedding language. To put it simply I don't provide examples for this kind of thing because these tasks are for Lua in general, not specific to my VM. Go find some good generic Lua tutorials, then read the VM API documentation to figure out how to do what you need.
