### ISSUE TITLE
how can i require package in lua

### ISSUE THREAD

**Issue by jiangrzh** [milochristiansen/lua#31]
Thank you for your package! I want to migrating our lua script under this golang package from c api.
but i have no idea how to require module in lua. can you show me some example?

**Comment by milochristiansen** [comment]
If you are trying to expose a native API to scripts, but rather than always load the API you want the scripts to load it with `require`, `lua.(*State).Preload` is the function you want.

If you want to require a native API from native code so that it is already loaded before running your scripts, `lua.(*State).Require` is probably what you want. In same cases you may not want the setup `Require` does, for example modules that are loaded to global variables. In these cases you can often just run their loader functions with `lua.(*State).Call`. The standard library modules are designed to be loaded this way (check the docs for the `Open` function in any standard module).

If you have a script module you want to load with native or script code, you will need to write a module searcher. This library only ships with support for loading modules that are preloaded, although it does support adding more searchers. This works exactly like it does in standard Lua, you write a searcher function and add it to `package.searchers`. To load your package once you have a searcher, you simply need to load `lua/lmodpackage.Open` so that `require` is defined and `require` your module.

**Comment by jiangrzh** [comment]
yes，thank you，i want choose option 2，but want to know，how to append my own searcher into package.searchers ?

**Comment by milochristiansen** [comment]
Native:
```go
// Where l is your lua state and you have already loaded the packages module:
l.Push("package")
l.GetTableRaw(lua.GlobalsIndex) // Put the global "package" table on the stack.
l.Push("searchers")
l.GetTableRaw(-2) // Get "package.searchers" and put it on the stack
l.Push(l.Length(-1)+1) // Get length+1 of "package.searchers"
l.Push(<Your Searcher Function>) // Push your searcher onto the stack
l.SetTableRaw(-3) // Add your searcher to package.searchers
l.Pop(2) // Remove "package" and "package.searchers" from the stack
```
Script:
```lua
package.searchers[#package.searchers+1] = <Your Searcher Function>
```

As to what a searcher function is and how it works: [See the Lua reference manual](https://www.lua.org/manual/5.3/manual.html#6.3) The docs in [`lua/lmodpackage`](https://godoc.org/github.com/milochristiansen/lua/lmodpackage) will list anything that is non-standard about how packages are handled.
